/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the auditoria service. Represents a row in the &quot;ley_trans_auditoria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.co.csj.service.model.impl.auditoriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.co.csj.service.model.impl.auditoriaImpl}.
 * </p>
 *
 * @author Equipo
 * @see auditoria
 * @see com.co.csj.service.model.impl.auditoriaImpl
 * @see com.co.csj.service.model.impl.auditoriaModelImpl
 * @generated
 */
public interface auditoriaModel extends BaseModel<auditoria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a auditoria model instance should use the {@link auditoria} interface instead.
	 */

	/**
	 * Returns the primary key of this auditoria.
	 *
	 * @return the primary key of this auditoria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this auditoria.
	 *
	 * @param primaryKey the primary key of this auditoria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this auditoria.
	 *
	 * @return the ID of this auditoria
	 */
	public long getId();

	/**
	 * Sets the ID of this auditoria.
	 *
	 * @param id the ID of this auditoria
	 */
	public void setId(long id);

	/**
	 * Returns the modificado_por of this auditoria.
	 *
	 * @return the modificado_por of this auditoria
	 */
	@AutoEscape
	public String getModificado_por();

	/**
	 * Sets the modificado_por of this auditoria.
	 *
	 * @param modificado_por the modificado_por of this auditoria
	 */
	public void setModificado_por(String modificado_por);

	/**
	 * Returns the accion of this auditoria.
	 *
	 * @return the accion of this auditoria
	 */
	@AutoEscape
	public String getAccion();

	/**
	 * Sets the accion of this auditoria.
	 *
	 * @param accion the accion of this auditoria
	 */
	public void setAccion(String accion);

	/**
	 * Returns the campo_modifico of this auditoria.
	 *
	 * @return the campo_modifico of this auditoria
	 */
	@AutoEscape
	public String getCampo_modifico();

	/**
	 * Sets the campo_modifico of this auditoria.
	 *
	 * @param campo_modifico the campo_modifico of this auditoria
	 */
	public void setCampo_modifico(String campo_modifico);

	/**
	 * Returns the fecha of this auditoria.
	 *
	 * @return the fecha of this auditoria
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this auditoria.
	 *
	 * @param fecha the fecha of this auditoria
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the ano_vigencia of this auditoria.
	 *
	 * @return the ano_vigencia of this auditoria
	 */
	public int getAno_vigencia();

	/**
	 * Sets the ano_vigencia of this auditoria.
	 *
	 * @param ano_vigencia the ano_vigencia of this auditoria
	 */
	public void setAno_vigencia(int ano_vigencia);

	/**
	 * Returns the cedula_funcionario of this auditoria.
	 *
	 * @return the cedula_funcionario of this auditoria
	 */
	@AutoEscape
	public String getCedula_funcionario();

	/**
	 * Sets the cedula_funcionario of this auditoria.
	 *
	 * @param cedula_funcionario the cedula_funcionario of this auditoria
	 */
	public void setCedula_funcionario(String cedula_funcionario);

	/**
	 * Returns the log_anterior of this auditoria.
	 *
	 * @return the log_anterior of this auditoria
	 */
	@AutoEscape
	public String getLog_anterior();

	/**
	 * Sets the log_anterior of this auditoria.
	 *
	 * @param log_anterior the log_anterior of this auditoria
	 */
	public void setLog_anterior(String log_anterior);

	/**
	 * Returns the log_nuevo of this auditoria.
	 *
	 * @return the log_nuevo of this auditoria
	 */
	@AutoEscape
	public String getLog_nuevo();

	/**
	 * Sets the log_nuevo of this auditoria.
	 *
	 * @param log_nuevo the log_nuevo of this auditoria
	 */
	public void setLog_nuevo(String log_nuevo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(auditoria auditoria);

	public int hashCode();

	public CacheModel<auditoria> toCacheModel();

	public auditoria toEscapedModel();

	public String toString();

	public String toXmlString();
}