/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the planificacion service. Represents a row in the &quot;ley_trans_planificacion_anio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.co.csj.service.model.impl.planificacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.co.csj.service.model.impl.planificacionImpl}.
 * </p>
 *
 * @author Equipo
 * @see planificacion
 * @see com.co.csj.service.model.impl.planificacionImpl
 * @see com.co.csj.service.model.impl.planificacionModelImpl
 * @generated
 */
public interface planificacionModel extends BaseModel<planificacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a planificacion model instance should use the {@link planificacion} interface instead.
	 */

	/**
	 * Returns the primary key of this planificacion.
	 *
	 * @return the primary key of this planificacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this planificacion.
	 *
	 * @param primaryKey the primary key of this planificacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this planificacion.
	 *
	 * @return the ID of this planificacion
	 */
	public long getId();

	/**
	 * Sets the ID of this planificacion.
	 *
	 * @param id the ID of this planificacion
	 */
	public void setId(long id);

	/**
	 * Returns the anhio of this planificacion.
	 *
	 * @return the anhio of this planificacion
	 */
	public int getAnhio();

	/**
	 * Sets the anhio of this planificacion.
	 *
	 * @param anhio the anhio of this planificacion
	 */
	public void setAnhio(int anhio);

	/**
	 * Returns the fecha_inicio of this planificacion.
	 *
	 * @return the fecha_inicio of this planificacion
	 */
	public Date getFecha_inicio();

	/**
	 * Sets the fecha_inicio of this planificacion.
	 *
	 * @param fecha_inicio the fecha_inicio of this planificacion
	 */
	public void setFecha_inicio(Date fecha_inicio);

	/**
	 * Returns the fecha_fin of this planificacion.
	 *
	 * @return the fecha_fin of this planificacion
	 */
	public Date getFecha_fin();

	/**
	 * Sets the fecha_fin of this planificacion.
	 *
	 * @param fecha_fin the fecha_fin of this planificacion
	 */
	public void setFecha_fin(Date fecha_fin);

	/**
	 * Returns the usuario_finalizo of this planificacion.
	 *
	 * @return the usuario_finalizo of this planificacion
	 */
	@AutoEscape
	public String getUsuario_finalizo();

	/**
	 * Sets the usuario_finalizo of this planificacion.
	 *
	 * @param usuario_finalizo the usuario_finalizo of this planificacion
	 */
	public void setUsuario_finalizo(String usuario_finalizo);

	/**
	 * Returns the estado of this planificacion.
	 *
	 * @return the estado of this planificacion
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this planificacion.
	 *
	 * @param estado the estado of this planificacion
	 */
	public void setEstado(String estado);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(planificacion planificacion);

	public int hashCode();

	public CacheModel<planificacion> toCacheModel();

	public planificacion toEscapedModel();

	public String toString();

	public String toXmlString();
}