/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the publicaciones service. Represents a row in the &quot;ley_trans_publicaciones&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.co.csj.service.model.impl.publicacionesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.co.csj.service.model.impl.publicacionesImpl}.
 * </p>
 *
 * @author Equipo
 * @see publicaciones
 * @see com.co.csj.service.model.impl.publicacionesImpl
 * @see com.co.csj.service.model.impl.publicacionesModelImpl
 * @generated
 */
public interface publicacionesModel extends BaseModel<publicaciones> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a publicaciones model instance should use the {@link publicaciones} interface instead.
	 */

	/**
	 * Returns the primary key of this publicaciones.
	 *
	 * @return the primary key of this publicaciones
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this publicaciones.
	 *
	 * @param primaryKey the primary key of this publicaciones
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this publicaciones.
	 *
	 * @return the ID of this publicaciones
	 */
	public long getId();

	/**
	 * Sets the ID of this publicaciones.
	 *
	 * @param id the ID of this publicaciones
	 */
	public void setId(long id);

	/**
	 * Returns the fk_usuario of this publicaciones.
	 *
	 * @return the fk_usuario of this publicaciones
	 */
	@AutoEscape
	public String getFk_usuario();

	/**
	 * Sets the fk_usuario of this publicaciones.
	 *
	 * @param fk_usuario the fk_usuario of this publicaciones
	 */
	public void setFk_usuario(String fk_usuario);

	/**
	 * Returns the despacho_usuario of this publicaciones.
	 *
	 * @return the despacho_usuario of this publicaciones
	 */
	@AutoEscape
	public String getDespacho_usuario();

	/**
	 * Sets the despacho_usuario of this publicaciones.
	 *
	 * @param despacho_usuario the despacho_usuario of this publicaciones
	 */
	public void setDespacho_usuario(String despacho_usuario);

	/**
	 * Returns the archivo_hoja_vida of this publicaciones.
	 *
	 * @return the archivo_hoja_vida of this publicaciones
	 */
	@AutoEscape
	public String getArchivo_hoja_vida();

	/**
	 * Sets the archivo_hoja_vida of this publicaciones.
	 *
	 * @param archivo_hoja_vida the archivo_hoja_vida of this publicaciones
	 */
	public void setArchivo_hoja_vida(String archivo_hoja_vida);

	/**
	 * Returns the archivo_declaracion_renta of this publicaciones.
	 *
	 * @return the archivo_declaracion_renta of this publicaciones
	 */
	@AutoEscape
	public String getArchivo_declaracion_renta();

	/**
	 * Sets the archivo_declaracion_renta of this publicaciones.
	 *
	 * @param archivo_declaracion_renta the archivo_declaracion_renta of this publicaciones
	 */
	public void setArchivo_declaracion_renta(String archivo_declaracion_renta);

	/**
	 * Returns the archivo_formulario_bienes of this publicaciones.
	 *
	 * @return the archivo_formulario_bienes of this publicaciones
	 */
	@AutoEscape
	public String getArchivo_formulario_bienes();

	/**
	 * Sets the archivo_formulario_bienes of this publicaciones.
	 *
	 * @param archivo_formulario_bienes the archivo_formulario_bienes of this publicaciones
	 */
	public void setArchivo_formulario_bienes(String archivo_formulario_bienes);

	/**
	 * Returns the fecha_solicitud of this publicaciones.
	 *
	 * @return the fecha_solicitud of this publicaciones
	 */
	public Date getFecha_solicitud();

	/**
	 * Sets the fecha_solicitud of this publicaciones.
	 *
	 * @param fecha_solicitud the fecha_solicitud of this publicaciones
	 */
	public void setFecha_solicitud(Date fecha_solicitud);

	/**
	 * Returns the fecha_publicacion of this publicaciones.
	 *
	 * @return the fecha_publicacion of this publicaciones
	 */
	public Date getFecha_publicacion();

	/**
	 * Sets the fecha_publicacion of this publicaciones.
	 *
	 * @param fecha_publicacion the fecha_publicacion of this publicaciones
	 */
	public void setFecha_publicacion(Date fecha_publicacion);

	/**
	 * Returns the aprobado_por of this publicaciones.
	 *
	 * @return the aprobado_por of this publicaciones
	 */
	@AutoEscape
	public String getAprobado_por();

	/**
	 * Sets the aprobado_por of this publicaciones.
	 *
	 * @param aprobado_por the aprobado_por of this publicaciones
	 */
	public void setAprobado_por(String aprobado_por);

	/**
	 * Returns the fecha_negado of this publicaciones.
	 *
	 * @return the fecha_negado of this publicaciones
	 */
	public Date getFecha_negado();

	/**
	 * Sets the fecha_negado of this publicaciones.
	 *
	 * @param fecha_negado the fecha_negado of this publicaciones
	 */
	public void setFecha_negado(Date fecha_negado);

	/**
	 * Returns the negado_por of this publicaciones.
	 *
	 * @return the negado_por of this publicaciones
	 */
	@AutoEscape
	public String getNegado_por();

	/**
	 * Sets the negado_por of this publicaciones.
	 *
	 * @param negado_por the negado_por of this publicaciones
	 */
	public void setNegado_por(String negado_por);

	/**
	 * Returns the anhio_publicacion of this publicaciones.
	 *
	 * @return the anhio_publicacion of this publicaciones
	 */
	public int getAnhio_publicacion();

	/**
	 * Sets the anhio_publicacion of this publicaciones.
	 *
	 * @param anhio_publicacion the anhio_publicacion of this publicaciones
	 */
	public void setAnhio_publicacion(int anhio_publicacion);

	/**
	 * Returns the fecha_modificado of this publicaciones.
	 *
	 * @return the fecha_modificado of this publicaciones
	 */
	public Date getFecha_modificado();

	/**
	 * Sets the fecha_modificado of this publicaciones.
	 *
	 * @param fecha_modificado the fecha_modificado of this publicaciones
	 */
	public void setFecha_modificado(Date fecha_modificado);

	/**
	 * Returns the estatus of this publicaciones.
	 *
	 * @return the estatus of this publicaciones
	 */
	@AutoEscape
	public String getEstatus();

	/**
	 * Sets the estatus of this publicaciones.
	 *
	 * @param estatus the estatus of this publicaciones
	 */
	public void setEstatus(String estatus);

	/**
	 * Returns the causa_negado of this publicaciones.
	 *
	 * @return the causa_negado of this publicaciones
	 */
	@AutoEscape
	public String getCausa_negado();

	/**
	 * Sets the causa_negado of this publicaciones.
	 *
	 * @param causa_negado the causa_negado of this publicaciones
	 */
	public void setCausa_negado(String causa_negado);

	/**
	 * Returns the cargo of this publicaciones.
	 *
	 * @return the cargo of this publicaciones
	 */
	@AutoEscape
	public String getCargo();

	/**
	 * Sets the cargo of this publicaciones.
	 *
	 * @param cargo the cargo of this publicaciones
	 */
	public void setCargo(String cargo);

	/**
	 * Returns the retirado of this publicaciones.
	 *
	 * @return the retirado of this publicaciones
	 */
	@AutoEscape
	public String getRetirado();

	/**
	 * Sets the retirado of this publicaciones.
	 *
	 * @param retirado the retirado of this publicaciones
	 */
	public void setRetirado(String retirado);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(publicaciones publicaciones);

	public int hashCode();

	public CacheModel<publicaciones> toCacheModel();

	public publicaciones toEscapedModel();

	public String toString();

	public String toXmlString();
}