/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the usuario_data service. Represents a row in the &quot;ley_trans_funcionario_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.co.csj.service.model.impl.usuario_dataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.co.csj.service.model.impl.usuario_dataImpl}.
 * </p>
 *
 * @author Equipo
 * @see usuario_data
 * @see com.co.csj.service.model.impl.usuario_dataImpl
 * @see com.co.csj.service.model.impl.usuario_dataModelImpl
 * @generated
 */
public interface usuario_dataModel extends BaseModel<usuario_data> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a usuario_data model instance should use the {@link usuario_data} interface instead.
	 */

	/**
	 * Returns the primary key of this usuario_data.
	 *
	 * @return the primary key of this usuario_data
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this usuario_data.
	 *
	 * @param primaryKey the primary key of this usuario_data
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the numero documento of this usuario_data.
	 *
	 * @return the numero documento of this usuario_data
	 */
	@AutoEscape
	public String getNumeroDocumento();

	/**
	 * Sets the numero documento of this usuario_data.
	 *
	 * @param numeroDocumento the numero documento of this usuario_data
	 */
	public void setNumeroDocumento(String numeroDocumento);

	/**
	 * Returns the tipo documento of this usuario_data.
	 *
	 * @return the tipo documento of this usuario_data
	 */
	@AutoEscape
	public String getTipoDocumento();

	/**
	 * Sets the tipo documento of this usuario_data.
	 *
	 * @param tipoDocumento the tipo documento of this usuario_data
	 */
	public void setTipoDocumento(String tipoDocumento);

	/**
	 * Returns the nombres of this usuario_data.
	 *
	 * @return the nombres of this usuario_data
	 */
	@AutoEscape
	public String getNombres();

	/**
	 * Sets the nombres of this usuario_data.
	 *
	 * @param nombres the nombres of this usuario_data
	 */
	public void setNombres(String nombres);

	/**
	 * Returns the apellidos of this usuario_data.
	 *
	 * @return the apellidos of this usuario_data
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this usuario_data.
	 *
	 * @param apellidos the apellidos of this usuario_data
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the cargo of this usuario_data.
	 *
	 * @return the cargo of this usuario_data
	 */
	@AutoEscape
	public String getCargo();

	/**
	 * Sets the cargo of this usuario_data.
	 *
	 * @param cargo the cargo of this usuario_data
	 */
	public void setCargo(String cargo);

	/**
	 * Returns the fecha registro of this usuario_data.
	 *
	 * @return the fecha registro of this usuario_data
	 */
	public Date getFechaRegistro();

	/**
	 * Sets the fecha registro of this usuario_data.
	 *
	 * @param fechaRegistro the fecha registro of this usuario_data
	 */
	public void setFechaRegistro(Date fechaRegistro);

	/**
	 * Returns the fecha modificacion of this usuario_data.
	 *
	 * @return the fecha modificacion of this usuario_data
	 */
	public Date getFechaModificacion();

	/**
	 * Sets the fecha modificacion of this usuario_data.
	 *
	 * @param fechaModificacion the fecha modificacion of this usuario_data
	 */
	public void setFechaModificacion(Date fechaModificacion);

	/**
	 * Returns the datos_personales of this usuario_data.
	 *
	 * @return the datos_personales of this usuario_data
	 */
	@AutoEscape
	public String getDatos_personales();

	/**
	 * Sets the datos_personales of this usuario_data.
	 *
	 * @param datos_personales the datos_personales of this usuario_data
	 */
	public void setDatos_personales(String datos_personales);

	/**
	 * Returns the despacho of this usuario_data.
	 *
	 * @return the despacho of this usuario_data
	 */
	@AutoEscape
	public String getDespacho();

	/**
	 * Sets the despacho of this usuario_data.
	 *
	 * @param despacho the despacho of this usuario_data
	 */
	public void setDespacho(String despacho);

	/**
	 * Returns the formacion_academica of this usuario_data.
	 *
	 * @return the formacion_academica of this usuario_data
	 */
	@AutoEscape
	public String getFormacion_academica();

	/**
	 * Sets the formacion_academica of this usuario_data.
	 *
	 * @param formacion_academica the formacion_academica of this usuario_data
	 */
	public void setFormacion_academica(String formacion_academica);

	/**
	 * Returns the experiencia_laboral of this usuario_data.
	 *
	 * @return the experiencia_laboral of this usuario_data
	 */
	@AutoEscape
	public String getExperiencia_laboral();

	/**
	 * Sets the experiencia_laboral of this usuario_data.
	 *
	 * @param experiencia_laboral the experiencia_laboral of this usuario_data
	 */
	public void setExperiencia_laboral(String experiencia_laboral);

	/**
	 * Returns the tiempo_experiencia of this usuario_data.
	 *
	 * @return the tiempo_experiencia of this usuario_data
	 */
	@AutoEscape
	public String getTiempo_experiencia();

	/**
	 * Sets the tiempo_experiencia of this usuario_data.
	 *
	 * @param tiempo_experiencia the tiempo_experiencia of this usuario_data
	 */
	public void setTiempo_experiencia(String tiempo_experiencia);

	/**
	 * Returns the bienes_y_rentas of this usuario_data.
	 *
	 * @return the bienes_y_rentas of this usuario_data
	 */
	@AutoEscape
	public String getBienes_y_rentas();

	/**
	 * Sets the bienes_y_rentas of this usuario_data.
	 *
	 * @param bienes_y_rentas the bienes_y_rentas of this usuario_data
	 */
	public void setBienes_y_rentas(String bienes_y_rentas);

	/**
	 * Returns the informacion_complementaria of this usuario_data.
	 *
	 * @return the informacion_complementaria of this usuario_data
	 */
	@AutoEscape
	public String getInformacion_complementaria();

	/**
	 * Sets the informacion_complementaria of this usuario_data.
	 *
	 * @param informacion_complementaria the informacion_complementaria of this usuario_data
	 */
	public void setInformacion_complementaria(String informacion_complementaria);

	/**
	 * Returns the conflicto_intereses of this usuario_data.
	 *
	 * @return the conflicto_intereses of this usuario_data
	 */
	@AutoEscape
	public String getConflicto_intereses();

	/**
	 * Sets the conflicto_intereses of this usuario_data.
	 *
	 * @param conflicto_intereses the conflicto_intereses of this usuario_data
	 */
	public void setConflicto_intereses(String conflicto_intereses);

	/**
	 * Returns the archivo_declaracion_renta of this usuario_data.
	 *
	 * @return the archivo_declaracion_renta of this usuario_data
	 */
	@AutoEscape
	public String getArchivo_declaracion_renta();

	/**
	 * Sets the archivo_declaracion_renta of this usuario_data.
	 *
	 * @param archivo_declaracion_renta the archivo_declaracion_renta of this usuario_data
	 */
	public void setArchivo_declaracion_renta(String archivo_declaracion_renta);

	/**
	 * Returns the archivo_formulario_bienes of this usuario_data.
	 *
	 * @return the archivo_formulario_bienes of this usuario_data
	 */
	@AutoEscape
	public String getArchivo_formulario_bienes();

	/**
	 * Sets the archivo_formulario_bienes of this usuario_data.
	 *
	 * @param archivo_formulario_bienes the archivo_formulario_bienes of this usuario_data
	 */
	public void setArchivo_formulario_bienes(String archivo_formulario_bienes);

	/**
	 * Returns the archivo_hoja_vida of this usuario_data.
	 *
	 * @return the archivo_hoja_vida of this usuario_data
	 */
	@AutoEscape
	public String getArchivo_hoja_vida();

	/**
	 * Sets the archivo_hoja_vida of this usuario_data.
	 *
	 * @param archivo_hoja_vida the archivo_hoja_vida of this usuario_data
	 */
	public void setArchivo_hoja_vida(String archivo_hoja_vida);

	/**
	 * Returns the porcentaje_dp of this usuario_data.
	 *
	 * @return the porcentaje_dp of this usuario_data
	 */
	public double getPorcentaje_dp();

	/**
	 * Sets the porcentaje_dp of this usuario_data.
	 *
	 * @param porcentaje_dp the porcentaje_dp of this usuario_data
	 */
	public void setPorcentaje_dp(double porcentaje_dp);

	/**
	 * Returns the porcentaje_fa of this usuario_data.
	 *
	 * @return the porcentaje_fa of this usuario_data
	 */
	public double getPorcentaje_fa();

	/**
	 * Sets the porcentaje_fa of this usuario_data.
	 *
	 * @param porcentaje_fa the porcentaje_fa of this usuario_data
	 */
	public void setPorcentaje_fa(double porcentaje_fa);

	/**
	 * Returns the porcentaje_el of this usuario_data.
	 *
	 * @return the porcentaje_el of this usuario_data
	 */
	public double getPorcentaje_el();

	/**
	 * Sets the porcentaje_el of this usuario_data.
	 *
	 * @param porcentaje_el the porcentaje_el of this usuario_data
	 */
	public void setPorcentaje_el(double porcentaje_el);

	/**
	 * Returns the porcentaje_te of this usuario_data.
	 *
	 * @return the porcentaje_te of this usuario_data
	 */
	public double getPorcentaje_te();

	/**
	 * Sets the porcentaje_te of this usuario_data.
	 *
	 * @param porcentaje_te the porcentaje_te of this usuario_data
	 */
	public void setPorcentaje_te(double porcentaje_te);

	/**
	 * Returns the porcentaje_br of this usuario_data.
	 *
	 * @return the porcentaje_br of this usuario_data
	 */
	public double getPorcentaje_br();

	/**
	 * Sets the porcentaje_br of this usuario_data.
	 *
	 * @param porcentaje_br the porcentaje_br of this usuario_data
	 */
	public void setPorcentaje_br(double porcentaje_br);

	/**
	 * Returns the porcentaje_ic of this usuario_data.
	 *
	 * @return the porcentaje_ic of this usuario_data
	 */
	public double getPorcentaje_ic();

	/**
	 * Sets the porcentaje_ic of this usuario_data.
	 *
	 * @param porcentaje_ic the porcentaje_ic of this usuario_data
	 */
	public void setPorcentaje_ic(double porcentaje_ic);

	/**
	 * Returns the porcentaje_ci of this usuario_data.
	 *
	 * @return the porcentaje_ci of this usuario_data
	 */
	public double getPorcentaje_ci();

	/**
	 * Sets the porcentaje_ci of this usuario_data.
	 *
	 * @param porcentaje_ci the porcentaje_ci of this usuario_data
	 */
	public void setPorcentaje_ci(double porcentaje_ci);

	/**
	 * Returns the retirado of this usuario_data.
	 *
	 * @return the retirado of this usuario_data
	 */
	@AutoEscape
	public String getRetirado();

	/**
	 * Sets the retirado of this usuario_data.
	 *
	 * @param retirado the retirado of this usuario_data
	 */
	public void setRetirado(String retirado);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(usuario_data usuario_data);

	public int hashCode();

	public CacheModel<usuario_data> toCacheModel();

	public usuario_data toEscapedModel();

	public String toString();

	public String toXmlString();
}