/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model.impl;

import com.co.csj.service.model.correos;
import com.co.csj.service.model.correosModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the correos service. Represents a row in the &quot;ley_trans_correos_depurado&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.co.csj.service.model.correosModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link correosImpl}.
 * </p>
 *
 * @author Equipo
 * @see correosImpl
 * @see com.co.csj.service.model.correos
 * @see com.co.csj.service.model.correosModel
 * @generated
 */
public class correosModelImpl extends BaseModelImpl<correos>
	implements correosModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a correos model instance should use the {@link com.co.csj.service.model.correos} interface instead.
	 */
	public static final String TABLE_NAME = "ley_trans_correos_depurado";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "CuentaCorreo", Types.VARCHAR },
			{ "nombre1", Types.VARCHAR },
			{ "apellido", Types.VARCHAR },
			{ "cargo", Types.VARCHAR },
			{ "cedulaResponsable", Types.VARCHAR },
			{ "codigoDespacho", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ley_trans_correos_depurado (id LONG not null primary key IDENTITY,CuentaCorreo VARCHAR(75) null,nombre1 VARCHAR(75) null,apellido VARCHAR(75) null,cargo VARCHAR(75) null,cedulaResponsable VARCHAR(75) null,codigoDespacho VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ley_trans_correos_depurado";
	public static final String DATA_SOURCE = "appsportal";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.co.csj.service.model.correos"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.co.csj.service.model.correos"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.co.csj.service.model.correos"),
			true);
	public static long CEDULARESPONSABLE_COLUMN_BITMASK = 1L;
	public static long CUENTACORREO_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.co.csj.service.model.correos"));

	public correosModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return correos.class;
	}

	public String getModelClassName() {
		return correos.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("cuentaCorreo", getCuentaCorreo());
		attributes.put("nombre1", getNombre1());
		attributes.put("apellido", getApellido());
		attributes.put("cargo", getCargo());
		attributes.put("cedulaResponsable", getCedulaResponsable());
		attributes.put("codigoDespacho", getCodigoDespacho());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String cuentaCorreo = (String)attributes.get("cuentaCorreo");

		if (cuentaCorreo != null) {
			setCuentaCorreo(cuentaCorreo);
		}

		String nombre1 = (String)attributes.get("nombre1");

		if (nombre1 != null) {
			setNombre1(nombre1);
		}

		String apellido = (String)attributes.get("apellido");

		if (apellido != null) {
			setApellido(apellido);
		}

		String cargo = (String)attributes.get("cargo");

		if (cargo != null) {
			setCargo(cargo);
		}

		String cedulaResponsable = (String)attributes.get("cedulaResponsable");

		if (cedulaResponsable != null) {
			setCedulaResponsable(cedulaResponsable);
		}

		String codigoDespacho = (String)attributes.get("codigoDespacho");

		if (codigoDespacho != null) {
			setCodigoDespacho(codigoDespacho);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getCuentaCorreo() {
		if (_cuentaCorreo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cuentaCorreo;
		}
	}

	public void setCuentaCorreo(String cuentaCorreo) {
		_columnBitmask |= CUENTACORREO_COLUMN_BITMASK;

		if (_originalCuentaCorreo == null) {
			_originalCuentaCorreo = _cuentaCorreo;
		}

		_cuentaCorreo = cuentaCorreo;
	}

	public String getOriginalCuentaCorreo() {
		return GetterUtil.getString(_originalCuentaCorreo);
	}

	public String getNombre1() {
		if (_nombre1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre1;
		}
	}

	public void setNombre1(String nombre1) {
		_nombre1 = nombre1;
	}

	public String getApellido() {
		if (_apellido == null) {
			return StringPool.BLANK;
		}
		else {
			return _apellido;
		}
	}

	public void setApellido(String apellido) {
		_apellido = apellido;
	}

	public String getCargo() {
		if (_cargo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cargo;
		}
	}

	public void setCargo(String cargo) {
		_cargo = cargo;
	}

	public String getCedulaResponsable() {
		if (_cedulaResponsable == null) {
			return StringPool.BLANK;
		}
		else {
			return _cedulaResponsable;
		}
	}

	public void setCedulaResponsable(String cedulaResponsable) {
		_columnBitmask |= CEDULARESPONSABLE_COLUMN_BITMASK;

		if (_originalCedulaResponsable == null) {
			_originalCedulaResponsable = _cedulaResponsable;
		}

		_cedulaResponsable = cedulaResponsable;
	}

	public String getOriginalCedulaResponsable() {
		return GetterUtil.getString(_originalCedulaResponsable);
	}

	public String getCodigoDespacho() {
		if (_codigoDespacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoDespacho;
		}
	}

	public void setCodigoDespacho(String codigoDespacho) {
		_codigoDespacho = codigoDespacho;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			correos.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public correos toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (correos)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		correosImpl correosImpl = new correosImpl();

		correosImpl.setId(getId());
		correosImpl.setCuentaCorreo(getCuentaCorreo());
		correosImpl.setNombre1(getNombre1());
		correosImpl.setApellido(getApellido());
		correosImpl.setCargo(getCargo());
		correosImpl.setCedulaResponsable(getCedulaResponsable());
		correosImpl.setCodigoDespacho(getCodigoDespacho());

		correosImpl.resetOriginalValues();

		return correosImpl;
	}

	public int compareTo(correos correos) {
		long primaryKey = correos.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		correos correos = null;

		try {
			correos = (correos)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = correos.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		correosModelImpl correosModelImpl = this;

		correosModelImpl._originalCuentaCorreo = correosModelImpl._cuentaCorreo;

		correosModelImpl._originalCedulaResponsable = correosModelImpl._cedulaResponsable;

		correosModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<correos> toCacheModel() {
		correosCacheModel correosCacheModel = new correosCacheModel();

		correosCacheModel.id = getId();

		correosCacheModel.cuentaCorreo = getCuentaCorreo();

		String cuentaCorreo = correosCacheModel.cuentaCorreo;

		if ((cuentaCorreo != null) && (cuentaCorreo.length() == 0)) {
			correosCacheModel.cuentaCorreo = null;
		}

		correosCacheModel.nombre1 = getNombre1();

		String nombre1 = correosCacheModel.nombre1;

		if ((nombre1 != null) && (nombre1.length() == 0)) {
			correosCacheModel.nombre1 = null;
		}

		correosCacheModel.apellido = getApellido();

		String apellido = correosCacheModel.apellido;

		if ((apellido != null) && (apellido.length() == 0)) {
			correosCacheModel.apellido = null;
		}

		correosCacheModel.cargo = getCargo();

		String cargo = correosCacheModel.cargo;

		if ((cargo != null) && (cargo.length() == 0)) {
			correosCacheModel.cargo = null;
		}

		correosCacheModel.cedulaResponsable = getCedulaResponsable();

		String cedulaResponsable = correosCacheModel.cedulaResponsable;

		if ((cedulaResponsable != null) && (cedulaResponsable.length() == 0)) {
			correosCacheModel.cedulaResponsable = null;
		}

		correosCacheModel.codigoDespacho = getCodigoDespacho();

		String codigoDespacho = correosCacheModel.codigoDespacho;

		if ((codigoDespacho != null) && (codigoDespacho.length() == 0)) {
			correosCacheModel.codigoDespacho = null;
		}

		return correosCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", cuentaCorreo=");
		sb.append(getCuentaCorreo());
		sb.append(", nombre1=");
		sb.append(getNombre1());
		sb.append(", apellido=");
		sb.append(getApellido());
		sb.append(", cargo=");
		sb.append(getCargo());
		sb.append(", cedulaResponsable=");
		sb.append(getCedulaResponsable());
		sb.append(", codigoDespacho=");
		sb.append(getCodigoDespacho());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.co.csj.service.model.correos");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cuentaCorreo</column-name><column-value><![CDATA[");
		sb.append(getCuentaCorreo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre1</column-name><column-value><![CDATA[");
		sb.append(getNombre1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellido</column-name><column-value><![CDATA[");
		sb.append(getApellido());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargo</column-name><column-value><![CDATA[");
		sb.append(getCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cedulaResponsable</column-name><column-value><![CDATA[");
		sb.append(getCedulaResponsable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoDespacho</column-name><column-value><![CDATA[");
		sb.append(getCodigoDespacho());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = correos.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			correos.class
		};
	private long _id;
	private String _cuentaCorreo;
	private String _originalCuentaCorreo;
	private String _nombre1;
	private String _apellido;
	private String _cargo;
	private String _cedulaResponsable;
	private String _originalCedulaResponsable;
	private String _codigoDespacho;
	private long _columnBitmask;
	private correos _escapedModelProxy;
}