/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model.impl;

import com.co.csj.service.model.planificacion;
import com.co.csj.service.model.planificacionModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the planificacion service. Represents a row in the &quot;ley_trans_planificacion_anio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.co.csj.service.model.planificacionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link planificacionImpl}.
 * </p>
 *
 * @author Equipo
 * @see planificacionImpl
 * @see com.co.csj.service.model.planificacion
 * @see com.co.csj.service.model.planificacionModel
 * @generated
 */
public class planificacionModelImpl extends BaseModelImpl<planificacion>
	implements planificacionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a planificacion model instance should use the {@link com.co.csj.service.model.planificacion} interface instead.
	 */
	public static final String TABLE_NAME = "ley_trans_planificacion_anio";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "anhio", Types.INTEGER },
			{ "fecha_inicio", Types.TIMESTAMP },
			{ "fecha_fin", Types.TIMESTAMP },
			{ "usuario_finalizo", Types.VARCHAR },
			{ "estado", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ley_trans_planificacion_anio (id LONG not null primary key IDENTITY,anhio INTEGER,fecha_inicio DATE null,fecha_fin DATE null,usuario_finalizo VARCHAR(75) null,estado VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ley_trans_planificacion_anio";
	public static final String DATA_SOURCE = "appsportal";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.co.csj.service.model.planificacion"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.co.csj.service.model.planificacion"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.co.csj.service.model.planificacion"),
			true);
	public static long ESTADO_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.co.csj.service.model.planificacion"));

	public planificacionModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return planificacion.class;
	}

	public String getModelClassName() {
		return planificacion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("anhio", getAnhio());
		attributes.put("fecha_inicio", getFecha_inicio());
		attributes.put("fecha_fin", getFecha_fin());
		attributes.put("usuario_finalizo", getUsuario_finalizo());
		attributes.put("estado", getEstado());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Integer anhio = (Integer)attributes.get("anhio");

		if (anhio != null) {
			setAnhio(anhio);
		}

		Date fecha_inicio = (Date)attributes.get("fecha_inicio");

		if (fecha_inicio != null) {
			setFecha_inicio(fecha_inicio);
		}

		Date fecha_fin = (Date)attributes.get("fecha_fin");

		if (fecha_fin != null) {
			setFecha_fin(fecha_fin);
		}

		String usuario_finalizo = (String)attributes.get("usuario_finalizo");

		if (usuario_finalizo != null) {
			setUsuario_finalizo(usuario_finalizo);
		}

		String estado = (String)attributes.get("estado");

		if (estado != null) {
			setEstado(estado);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public int getAnhio() {
		return _anhio;
	}

	public void setAnhio(int anhio) {
		_anhio = anhio;
	}

	public Date getFecha_inicio() {
		return _fecha_inicio;
	}

	public void setFecha_inicio(Date fecha_inicio) {
		_fecha_inicio = fecha_inicio;
	}

	public Date getFecha_fin() {
		return _fecha_fin;
	}

	public void setFecha_fin(Date fecha_fin) {
		_fecha_fin = fecha_fin;
	}

	public String getUsuario_finalizo() {
		if (_usuario_finalizo == null) {
			return StringPool.BLANK;
		}
		else {
			return _usuario_finalizo;
		}
	}

	public void setUsuario_finalizo(String usuario_finalizo) {
		_usuario_finalizo = usuario_finalizo;
	}

	public String getEstado() {
		if (_estado == null) {
			return StringPool.BLANK;
		}
		else {
			return _estado;
		}
	}

	public void setEstado(String estado) {
		_columnBitmask |= ESTADO_COLUMN_BITMASK;

		if (_originalEstado == null) {
			_originalEstado = _estado;
		}

		_estado = estado;
	}

	public String getOriginalEstado() {
		return GetterUtil.getString(_originalEstado);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			planificacion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public planificacion toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (planificacion)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		planificacionImpl planificacionImpl = new planificacionImpl();

		planificacionImpl.setId(getId());
		planificacionImpl.setAnhio(getAnhio());
		planificacionImpl.setFecha_inicio(getFecha_inicio());
		planificacionImpl.setFecha_fin(getFecha_fin());
		planificacionImpl.setUsuario_finalizo(getUsuario_finalizo());
		planificacionImpl.setEstado(getEstado());

		planificacionImpl.resetOriginalValues();

		return planificacionImpl;
	}

	public int compareTo(planificacion planificacion) {
		long primaryKey = planificacion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		planificacion planificacion = null;

		try {
			planificacion = (planificacion)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = planificacion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		planificacionModelImpl planificacionModelImpl = this;

		planificacionModelImpl._originalEstado = planificacionModelImpl._estado;

		planificacionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<planificacion> toCacheModel() {
		planificacionCacheModel planificacionCacheModel = new planificacionCacheModel();

		planificacionCacheModel.id = getId();

		planificacionCacheModel.anhio = getAnhio();

		Date fecha_inicio = getFecha_inicio();

		if (fecha_inicio != null) {
			planificacionCacheModel.fecha_inicio = fecha_inicio.getTime();
		}
		else {
			planificacionCacheModel.fecha_inicio = Long.MIN_VALUE;
		}

		Date fecha_fin = getFecha_fin();

		if (fecha_fin != null) {
			planificacionCacheModel.fecha_fin = fecha_fin.getTime();
		}
		else {
			planificacionCacheModel.fecha_fin = Long.MIN_VALUE;
		}

		planificacionCacheModel.usuario_finalizo = getUsuario_finalizo();

		String usuario_finalizo = planificacionCacheModel.usuario_finalizo;

		if ((usuario_finalizo != null) && (usuario_finalizo.length() == 0)) {
			planificacionCacheModel.usuario_finalizo = null;
		}

		planificacionCacheModel.estado = getEstado();

		String estado = planificacionCacheModel.estado;

		if ((estado != null) && (estado.length() == 0)) {
			planificacionCacheModel.estado = null;
		}

		return planificacionCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", anhio=");
		sb.append(getAnhio());
		sb.append(", fecha_inicio=");
		sb.append(getFecha_inicio());
		sb.append(", fecha_fin=");
		sb.append(getFecha_fin());
		sb.append(", usuario_finalizo=");
		sb.append(getUsuario_finalizo());
		sb.append(", estado=");
		sb.append(getEstado());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.co.csj.service.model.planificacion");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhio</column-name><column-value><![CDATA[");
		sb.append(getAnhio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_inicio</column-name><column-value><![CDATA[");
		sb.append(getFecha_inicio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_fin</column-name><column-value><![CDATA[");
		sb.append(getFecha_fin());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>usuario_finalizo</column-name><column-value><![CDATA[");
		sb.append(getUsuario_finalizo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estado</column-name><column-value><![CDATA[");
		sb.append(getEstado());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = planificacion.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			planificacion.class
		};
	private long _id;
	private int _anhio;
	private Date _fecha_inicio;
	private Date _fecha_fin;
	private String _usuario_finalizo;
	private String _estado;
	private String _originalEstado;
	private long _columnBitmask;
	private planificacion _escapedModelProxy;
}