/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model.impl;

import com.co.csj.service.model.publicaciones;
import com.co.csj.service.model.publicacionesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the publicaciones service. Represents a row in the &quot;ley_trans_publicaciones&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.co.csj.service.model.publicacionesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link publicacionesImpl}.
 * </p>
 *
 * @author Equipo
 * @see publicacionesImpl
 * @see com.co.csj.service.model.publicaciones
 * @see com.co.csj.service.model.publicacionesModel
 * @generated
 */
public class publicacionesModelImpl extends BaseModelImpl<publicaciones>
	implements publicacionesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a publicaciones model instance should use the {@link com.co.csj.service.model.publicaciones} interface instead.
	 */
	public static final String TABLE_NAME = "ley_trans_publicaciones";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "fk_usuario", Types.VARCHAR },
			{ "despacho_usuario", Types.VARCHAR },
			{ "archivo_hoja_vida", Types.VARCHAR },
			{ "archivo_declaracion_renta", Types.VARCHAR },
			{ "archivo_formulario_bienes", Types.VARCHAR },
			{ "fecha_solicitud", Types.TIMESTAMP },
			{ "fecha_publicacion", Types.TIMESTAMP },
			{ "aprobado_por", Types.VARCHAR },
			{ "fecha_negado", Types.TIMESTAMP },
			{ "negado_por", Types.VARCHAR },
			{ "anhio_publicacion", Types.INTEGER },
			{ "fecha_modificado", Types.TIMESTAMP },
			{ "estatus", Types.VARCHAR },
			{ "causa_negado", Types.VARCHAR },
			{ "cargo", Types.VARCHAR },
			{ "retirado", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ley_trans_publicaciones (id LONG not null primary key IDENTITY,fk_usuario VARCHAR(75) null,despacho_usuario VARCHAR(75) null,archivo_hoja_vida VARCHAR(75) null,archivo_declaracion_renta VARCHAR(75) null,archivo_formulario_bienes VARCHAR(75) null,fecha_solicitud DATE null,fecha_publicacion DATE null,aprobado_por VARCHAR(75) null,fecha_negado DATE null,negado_por VARCHAR(75) null,anhio_publicacion INTEGER,fecha_modificado DATE null,estatus VARCHAR(75) null,causa_negado VARCHAR(75) null,cargo VARCHAR(75) null,retirado VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ley_trans_publicaciones";
	public static final String DATA_SOURCE = "appsportal";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.co.csj.service.model.publicaciones"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.co.csj.service.model.publicaciones"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.co.csj.service.model.publicaciones"),
			true);
	public static long ANHIO_PUBLICACION_COLUMN_BITMASK = 1L;
	public static long ESTATUS_COLUMN_BITMASK = 2L;
	public static long FK_USUARIO_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.co.csj.service.model.publicaciones"));

	public publicacionesModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return publicaciones.class;
	}

	public String getModelClassName() {
		return publicaciones.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("fk_usuario", getFk_usuario());
		attributes.put("despacho_usuario", getDespacho_usuario());
		attributes.put("archivo_hoja_vida", getArchivo_hoja_vida());
		attributes.put("archivo_declaracion_renta",
			getArchivo_declaracion_renta());
		attributes.put("archivo_formulario_bienes",
			getArchivo_formulario_bienes());
		attributes.put("fecha_solicitud", getFecha_solicitud());
		attributes.put("fecha_publicacion", getFecha_publicacion());
		attributes.put("aprobado_por", getAprobado_por());
		attributes.put("fecha_negado", getFecha_negado());
		attributes.put("negado_por", getNegado_por());
		attributes.put("anhio_publicacion", getAnhio_publicacion());
		attributes.put("fecha_modificado", getFecha_modificado());
		attributes.put("estatus", getEstatus());
		attributes.put("causa_negado", getCausa_negado());
		attributes.put("cargo", getCargo());
		attributes.put("retirado", getRetirado());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String fk_usuario = (String)attributes.get("fk_usuario");

		if (fk_usuario != null) {
			setFk_usuario(fk_usuario);
		}

		String despacho_usuario = (String)attributes.get("despacho_usuario");

		if (despacho_usuario != null) {
			setDespacho_usuario(despacho_usuario);
		}

		String archivo_hoja_vida = (String)attributes.get("archivo_hoja_vida");

		if (archivo_hoja_vida != null) {
			setArchivo_hoja_vida(archivo_hoja_vida);
		}

		String archivo_declaracion_renta = (String)attributes.get(
				"archivo_declaracion_renta");

		if (archivo_declaracion_renta != null) {
			setArchivo_declaracion_renta(archivo_declaracion_renta);
		}

		String archivo_formulario_bienes = (String)attributes.get(
				"archivo_formulario_bienes");

		if (archivo_formulario_bienes != null) {
			setArchivo_formulario_bienes(archivo_formulario_bienes);
		}

		Date fecha_solicitud = (Date)attributes.get("fecha_solicitud");

		if (fecha_solicitud != null) {
			setFecha_solicitud(fecha_solicitud);
		}

		Date fecha_publicacion = (Date)attributes.get("fecha_publicacion");

		if (fecha_publicacion != null) {
			setFecha_publicacion(fecha_publicacion);
		}

		String aprobado_por = (String)attributes.get("aprobado_por");

		if (aprobado_por != null) {
			setAprobado_por(aprobado_por);
		}

		Date fecha_negado = (Date)attributes.get("fecha_negado");

		if (fecha_negado != null) {
			setFecha_negado(fecha_negado);
		}

		String negado_por = (String)attributes.get("negado_por");

		if (negado_por != null) {
			setNegado_por(negado_por);
		}

		Integer anhio_publicacion = (Integer)attributes.get("anhio_publicacion");

		if (anhio_publicacion != null) {
			setAnhio_publicacion(anhio_publicacion);
		}

		Date fecha_modificado = (Date)attributes.get("fecha_modificado");

		if (fecha_modificado != null) {
			setFecha_modificado(fecha_modificado);
		}

		String estatus = (String)attributes.get("estatus");

		if (estatus != null) {
			setEstatus(estatus);
		}

		String causa_negado = (String)attributes.get("causa_negado");

		if (causa_negado != null) {
			setCausa_negado(causa_negado);
		}

		String cargo = (String)attributes.get("cargo");

		if (cargo != null) {
			setCargo(cargo);
		}

		String retirado = (String)attributes.get("retirado");

		if (retirado != null) {
			setRetirado(retirado);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public String getFk_usuario() {
		if (_fk_usuario == null) {
			return StringPool.BLANK;
		}
		else {
			return _fk_usuario;
		}
	}

	public void setFk_usuario(String fk_usuario) {
		_columnBitmask |= FK_USUARIO_COLUMN_BITMASK;

		if (_originalFk_usuario == null) {
			_originalFk_usuario = _fk_usuario;
		}

		_fk_usuario = fk_usuario;
	}

	public String getOriginalFk_usuario() {
		return GetterUtil.getString(_originalFk_usuario);
	}

	public String getDespacho_usuario() {
		if (_despacho_usuario == null) {
			return StringPool.BLANK;
		}
		else {
			return _despacho_usuario;
		}
	}

	public void setDespacho_usuario(String despacho_usuario) {
		_despacho_usuario = despacho_usuario;
	}

	public String getArchivo_hoja_vida() {
		if (_archivo_hoja_vida == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_hoja_vida;
		}
	}

	public void setArchivo_hoja_vida(String archivo_hoja_vida) {
		_archivo_hoja_vida = archivo_hoja_vida;
	}

	public String getArchivo_declaracion_renta() {
		if (_archivo_declaracion_renta == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_declaracion_renta;
		}
	}

	public void setArchivo_declaracion_renta(String archivo_declaracion_renta) {
		_archivo_declaracion_renta = archivo_declaracion_renta;
	}

	public String getArchivo_formulario_bienes() {
		if (_archivo_formulario_bienes == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_formulario_bienes;
		}
	}

	public void setArchivo_formulario_bienes(String archivo_formulario_bienes) {
		_archivo_formulario_bienes = archivo_formulario_bienes;
	}

	public Date getFecha_solicitud() {
		return _fecha_solicitud;
	}

	public void setFecha_solicitud(Date fecha_solicitud) {
		_fecha_solicitud = fecha_solicitud;
	}

	public Date getFecha_publicacion() {
		return _fecha_publicacion;
	}

	public void setFecha_publicacion(Date fecha_publicacion) {
		_fecha_publicacion = fecha_publicacion;
	}

	public String getAprobado_por() {
		if (_aprobado_por == null) {
			return StringPool.BLANK;
		}
		else {
			return _aprobado_por;
		}
	}

	public void setAprobado_por(String aprobado_por) {
		_aprobado_por = aprobado_por;
	}

	public Date getFecha_negado() {
		return _fecha_negado;
	}

	public void setFecha_negado(Date fecha_negado) {
		_fecha_negado = fecha_negado;
	}

	public String getNegado_por() {
		if (_negado_por == null) {
			return StringPool.BLANK;
		}
		else {
			return _negado_por;
		}
	}

	public void setNegado_por(String negado_por) {
		_negado_por = negado_por;
	}

	public int getAnhio_publicacion() {
		return _anhio_publicacion;
	}

	public void setAnhio_publicacion(int anhio_publicacion) {
		_columnBitmask |= ANHIO_PUBLICACION_COLUMN_BITMASK;

		if (!_setOriginalAnhio_publicacion) {
			_setOriginalAnhio_publicacion = true;

			_originalAnhio_publicacion = _anhio_publicacion;
		}

		_anhio_publicacion = anhio_publicacion;
	}

	public int getOriginalAnhio_publicacion() {
		return _originalAnhio_publicacion;
	}

	public Date getFecha_modificado() {
		return _fecha_modificado;
	}

	public void setFecha_modificado(Date fecha_modificado) {
		_fecha_modificado = fecha_modificado;
	}

	public String getEstatus() {
		if (_estatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _estatus;
		}
	}

	public void setEstatus(String estatus) {
		_columnBitmask |= ESTATUS_COLUMN_BITMASK;

		if (_originalEstatus == null) {
			_originalEstatus = _estatus;
		}

		_estatus = estatus;
	}

	public String getOriginalEstatus() {
		return GetterUtil.getString(_originalEstatus);
	}

	public String getCausa_negado() {
		if (_causa_negado == null) {
			return StringPool.BLANK;
		}
		else {
			return _causa_negado;
		}
	}

	public void setCausa_negado(String causa_negado) {
		_causa_negado = causa_negado;
	}

	public String getCargo() {
		if (_cargo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cargo;
		}
	}

	public void setCargo(String cargo) {
		_cargo = cargo;
	}

	public String getRetirado() {
		if (_retirado == null) {
			return StringPool.BLANK;
		}
		else {
			return _retirado;
		}
	}

	public void setRetirado(String retirado) {
		_retirado = retirado;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			publicaciones.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public publicaciones toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (publicaciones)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		publicacionesImpl publicacionesImpl = new publicacionesImpl();

		publicacionesImpl.setId(getId());
		publicacionesImpl.setFk_usuario(getFk_usuario());
		publicacionesImpl.setDespacho_usuario(getDespacho_usuario());
		publicacionesImpl.setArchivo_hoja_vida(getArchivo_hoja_vida());
		publicacionesImpl.setArchivo_declaracion_renta(getArchivo_declaracion_renta());
		publicacionesImpl.setArchivo_formulario_bienes(getArchivo_formulario_bienes());
		publicacionesImpl.setFecha_solicitud(getFecha_solicitud());
		publicacionesImpl.setFecha_publicacion(getFecha_publicacion());
		publicacionesImpl.setAprobado_por(getAprobado_por());
		publicacionesImpl.setFecha_negado(getFecha_negado());
		publicacionesImpl.setNegado_por(getNegado_por());
		publicacionesImpl.setAnhio_publicacion(getAnhio_publicacion());
		publicacionesImpl.setFecha_modificado(getFecha_modificado());
		publicacionesImpl.setEstatus(getEstatus());
		publicacionesImpl.setCausa_negado(getCausa_negado());
		publicacionesImpl.setCargo(getCargo());
		publicacionesImpl.setRetirado(getRetirado());

		publicacionesImpl.resetOriginalValues();

		return publicacionesImpl;
	}

	public int compareTo(publicaciones publicaciones) {
		long primaryKey = publicaciones.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		publicaciones publicaciones = null;

		try {
			publicaciones = (publicaciones)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = publicaciones.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		publicacionesModelImpl publicacionesModelImpl = this;

		publicacionesModelImpl._originalFk_usuario = publicacionesModelImpl._fk_usuario;

		publicacionesModelImpl._originalAnhio_publicacion = publicacionesModelImpl._anhio_publicacion;

		publicacionesModelImpl._setOriginalAnhio_publicacion = false;

		publicacionesModelImpl._originalEstatus = publicacionesModelImpl._estatus;

		publicacionesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<publicaciones> toCacheModel() {
		publicacionesCacheModel publicacionesCacheModel = new publicacionesCacheModel();

		publicacionesCacheModel.id = getId();

		publicacionesCacheModel.fk_usuario = getFk_usuario();

		String fk_usuario = publicacionesCacheModel.fk_usuario;

		if ((fk_usuario != null) && (fk_usuario.length() == 0)) {
			publicacionesCacheModel.fk_usuario = null;
		}

		publicacionesCacheModel.despacho_usuario = getDespacho_usuario();

		String despacho_usuario = publicacionesCacheModel.despacho_usuario;

		if ((despacho_usuario != null) && (despacho_usuario.length() == 0)) {
			publicacionesCacheModel.despacho_usuario = null;
		}

		publicacionesCacheModel.archivo_hoja_vida = getArchivo_hoja_vida();

		String archivo_hoja_vida = publicacionesCacheModel.archivo_hoja_vida;

		if ((archivo_hoja_vida != null) && (archivo_hoja_vida.length() == 0)) {
			publicacionesCacheModel.archivo_hoja_vida = null;
		}

		publicacionesCacheModel.archivo_declaracion_renta = getArchivo_declaracion_renta();

		String archivo_declaracion_renta = publicacionesCacheModel.archivo_declaracion_renta;

		if ((archivo_declaracion_renta != null) &&
				(archivo_declaracion_renta.length() == 0)) {
			publicacionesCacheModel.archivo_declaracion_renta = null;
		}

		publicacionesCacheModel.archivo_formulario_bienes = getArchivo_formulario_bienes();

		String archivo_formulario_bienes = publicacionesCacheModel.archivo_formulario_bienes;

		if ((archivo_formulario_bienes != null) &&
				(archivo_formulario_bienes.length() == 0)) {
			publicacionesCacheModel.archivo_formulario_bienes = null;
		}

		Date fecha_solicitud = getFecha_solicitud();

		if (fecha_solicitud != null) {
			publicacionesCacheModel.fecha_solicitud = fecha_solicitud.getTime();
		}
		else {
			publicacionesCacheModel.fecha_solicitud = Long.MIN_VALUE;
		}

		Date fecha_publicacion = getFecha_publicacion();

		if (fecha_publicacion != null) {
			publicacionesCacheModel.fecha_publicacion = fecha_publicacion.getTime();
		}
		else {
			publicacionesCacheModel.fecha_publicacion = Long.MIN_VALUE;
		}

		publicacionesCacheModel.aprobado_por = getAprobado_por();

		String aprobado_por = publicacionesCacheModel.aprobado_por;

		if ((aprobado_por != null) && (aprobado_por.length() == 0)) {
			publicacionesCacheModel.aprobado_por = null;
		}

		Date fecha_negado = getFecha_negado();

		if (fecha_negado != null) {
			publicacionesCacheModel.fecha_negado = fecha_negado.getTime();
		}
		else {
			publicacionesCacheModel.fecha_negado = Long.MIN_VALUE;
		}

		publicacionesCacheModel.negado_por = getNegado_por();

		String negado_por = publicacionesCacheModel.negado_por;

		if ((negado_por != null) && (negado_por.length() == 0)) {
			publicacionesCacheModel.negado_por = null;
		}

		publicacionesCacheModel.anhio_publicacion = getAnhio_publicacion();

		Date fecha_modificado = getFecha_modificado();

		if (fecha_modificado != null) {
			publicacionesCacheModel.fecha_modificado = fecha_modificado.getTime();
		}
		else {
			publicacionesCacheModel.fecha_modificado = Long.MIN_VALUE;
		}

		publicacionesCacheModel.estatus = getEstatus();

		String estatus = publicacionesCacheModel.estatus;

		if ((estatus != null) && (estatus.length() == 0)) {
			publicacionesCacheModel.estatus = null;
		}

		publicacionesCacheModel.causa_negado = getCausa_negado();

		String causa_negado = publicacionesCacheModel.causa_negado;

		if ((causa_negado != null) && (causa_negado.length() == 0)) {
			publicacionesCacheModel.causa_negado = null;
		}

		publicacionesCacheModel.cargo = getCargo();

		String cargo = publicacionesCacheModel.cargo;

		if ((cargo != null) && (cargo.length() == 0)) {
			publicacionesCacheModel.cargo = null;
		}

		publicacionesCacheModel.retirado = getRetirado();

		String retirado = publicacionesCacheModel.retirado;

		if ((retirado != null) && (retirado.length() == 0)) {
			publicacionesCacheModel.retirado = null;
		}

		return publicacionesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(35);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", fk_usuario=");
		sb.append(getFk_usuario());
		sb.append(", despacho_usuario=");
		sb.append(getDespacho_usuario());
		sb.append(", archivo_hoja_vida=");
		sb.append(getArchivo_hoja_vida());
		sb.append(", archivo_declaracion_renta=");
		sb.append(getArchivo_declaracion_renta());
		sb.append(", archivo_formulario_bienes=");
		sb.append(getArchivo_formulario_bienes());
		sb.append(", fecha_solicitud=");
		sb.append(getFecha_solicitud());
		sb.append(", fecha_publicacion=");
		sb.append(getFecha_publicacion());
		sb.append(", aprobado_por=");
		sb.append(getAprobado_por());
		sb.append(", fecha_negado=");
		sb.append(getFecha_negado());
		sb.append(", negado_por=");
		sb.append(getNegado_por());
		sb.append(", anhio_publicacion=");
		sb.append(getAnhio_publicacion());
		sb.append(", fecha_modificado=");
		sb.append(getFecha_modificado());
		sb.append(", estatus=");
		sb.append(getEstatus());
		sb.append(", causa_negado=");
		sb.append(getCausa_negado());
		sb.append(", cargo=");
		sb.append(getCargo());
		sb.append(", retirado=");
		sb.append(getRetirado());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(55);

		sb.append("<model><model-name>");
		sb.append("com.co.csj.service.model.publicaciones");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fk_usuario</column-name><column-value><![CDATA[");
		sb.append(getFk_usuario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despacho_usuario</column-name><column-value><![CDATA[");
		sb.append(getDespacho_usuario());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_hoja_vida</column-name><column-value><![CDATA[");
		sb.append(getArchivo_hoja_vida());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_declaracion_renta</column-name><column-value><![CDATA[");
		sb.append(getArchivo_declaracion_renta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_formulario_bienes</column-name><column-value><![CDATA[");
		sb.append(getArchivo_formulario_bienes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_solicitud</column-name><column-value><![CDATA[");
		sb.append(getFecha_solicitud());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_publicacion</column-name><column-value><![CDATA[");
		sb.append(getFecha_publicacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>aprobado_por</column-name><column-value><![CDATA[");
		sb.append(getAprobado_por());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_negado</column-name><column-value><![CDATA[");
		sb.append(getFecha_negado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>negado_por</column-name><column-value><![CDATA[");
		sb.append(getNegado_por());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anhio_publicacion</column-name><column-value><![CDATA[");
		sb.append(getAnhio_publicacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fecha_modificado</column-name><column-value><![CDATA[");
		sb.append(getFecha_modificado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>estatus</column-name><column-value><![CDATA[");
		sb.append(getEstatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>causa_negado</column-name><column-value><![CDATA[");
		sb.append(getCausa_negado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargo</column-name><column-value><![CDATA[");
		sb.append(getCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>retirado</column-name><column-value><![CDATA[");
		sb.append(getRetirado());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = publicaciones.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			publicaciones.class
		};
	private long _id;
	private String _fk_usuario;
	private String _originalFk_usuario;
	private String _despacho_usuario;
	private String _archivo_hoja_vida;
	private String _archivo_declaracion_renta;
	private String _archivo_formulario_bienes;
	private Date _fecha_solicitud;
	private Date _fecha_publicacion;
	private String _aprobado_por;
	private Date _fecha_negado;
	private String _negado_por;
	private int _anhio_publicacion;
	private int _originalAnhio_publicacion;
	private boolean _setOriginalAnhio_publicacion;
	private Date _fecha_modificado;
	private String _estatus;
	private String _originalEstatus;
	private String _causa_negado;
	private String _cargo;
	private String _retirado;
	private long _columnBitmask;
	private publicaciones _escapedModelProxy;
}