/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.co.csj.service.model.impl;

import com.co.csj.service.model.usuario_data;
import com.co.csj.service.model.usuario_dataModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the usuario_data service. Represents a row in the &quot;ley_trans_funcionario_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.co.csj.service.model.usuario_dataModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link usuario_dataImpl}.
 * </p>
 *
 * @author Equipo
 * @see usuario_dataImpl
 * @see com.co.csj.service.model.usuario_data
 * @see com.co.csj.service.model.usuario_dataModel
 * @generated
 */
public class usuario_dataModelImpl extends BaseModelImpl<usuario_data>
	implements usuario_dataModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a usuario_data model instance should use the {@link com.co.csj.service.model.usuario_data} interface instead.
	 */
	public static final String TABLE_NAME = "ley_trans_funcionario_data";
	public static final Object[][] TABLE_COLUMNS = {
			{ "numero_documento", Types.VARCHAR },
			{ "tipo_documento", Types.VARCHAR },
			{ "nombres", Types.VARCHAR },
			{ "apellidos", Types.VARCHAR },
			{ "cargo", Types.VARCHAR },
			{ "fecha_registro", Types.TIMESTAMP },
			{ "fecha_modificacion", Types.TIMESTAMP },
			{ "datos_personales", Types.VARCHAR },
			{ "despacho", Types.VARCHAR },
			{ "formacion_academica", Types.VARCHAR },
			{ "experiencia_laboral", Types.VARCHAR },
			{ "tiempo_experiencia", Types.VARCHAR },
			{ "bienes_y_rentas", Types.VARCHAR },
			{ "informacion_complementaria", Types.VARCHAR },
			{ "conflicto_intereses", Types.VARCHAR },
			{ "archivo_declaracion_renta", Types.VARCHAR },
			{ "archivo_formulario_bienes", Types.VARCHAR },
			{ "archivo_hoja_vida", Types.VARCHAR },
			{ "porcentaje_dp", Types.DOUBLE },
			{ "porcentaje_fa", Types.DOUBLE },
			{ "porcentaje_el", Types.DOUBLE },
			{ "porcentaje_te", Types.DOUBLE },
			{ "porcentaje_br", Types.DOUBLE },
			{ "porcentaje_ic", Types.DOUBLE },
			{ "porcentaje_ci", Types.DOUBLE },
			{ "retirado", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table ley_trans_funcionario_data (numero_documento VARCHAR(75) not null primary key,tipo_documento VARCHAR(75) null,nombres VARCHAR(75) null,apellidos VARCHAR(75) null,cargo VARCHAR(75) null,fecha_registro DATE null,fecha_modificacion DATE null,datos_personales VARCHAR(75) null,despacho VARCHAR(75) null,formacion_academica VARCHAR(75) null,experiencia_laboral VARCHAR(75) null,tiempo_experiencia VARCHAR(75) null,bienes_y_rentas VARCHAR(75) null,informacion_complementaria VARCHAR(75) null,conflicto_intereses VARCHAR(75) null,archivo_declaracion_renta VARCHAR(75) null,archivo_formulario_bienes VARCHAR(75) null,archivo_hoja_vida VARCHAR(75) null,porcentaje_dp DOUBLE,porcentaje_fa DOUBLE,porcentaje_el DOUBLE,porcentaje_te DOUBLE,porcentaje_br DOUBLE,porcentaje_ic DOUBLE,porcentaje_ci DOUBLE,retirado VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table ley_trans_funcionario_data";
	public static final String DATA_SOURCE = "appsportal";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.co.csj.service.model.usuario_data"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.co.csj.service.model.usuario_data"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.co.csj.service.model.usuario_data"));

	public usuario_dataModelImpl() {
	}

	public String getPrimaryKey() {
		return _numeroDocumento;
	}

	public void setPrimaryKey(String primaryKey) {
		setNumeroDocumento(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _numeroDocumento;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return usuario_data.class;
	}

	public String getModelClassName() {
		return usuario_data.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("numeroDocumento", getNumeroDocumento());
		attributes.put("tipoDocumento", getTipoDocumento());
		attributes.put("nombres", getNombres());
		attributes.put("apellidos", getApellidos());
		attributes.put("cargo", getCargo());
		attributes.put("fechaRegistro", getFechaRegistro());
		attributes.put("fechaModificacion", getFechaModificacion());
		attributes.put("datos_personales", getDatos_personales());
		attributes.put("despacho", getDespacho());
		attributes.put("formacion_academica", getFormacion_academica());
		attributes.put("experiencia_laboral", getExperiencia_laboral());
		attributes.put("tiempo_experiencia", getTiempo_experiencia());
		attributes.put("bienes_y_rentas", getBienes_y_rentas());
		attributes.put("informacion_complementaria",
			getInformacion_complementaria());
		attributes.put("conflicto_intereses", getConflicto_intereses());
		attributes.put("archivo_declaracion_renta",
			getArchivo_declaracion_renta());
		attributes.put("archivo_formulario_bienes",
			getArchivo_formulario_bienes());
		attributes.put("archivo_hoja_vida", getArchivo_hoja_vida());
		attributes.put("porcentaje_dp", getPorcentaje_dp());
		attributes.put("porcentaje_fa", getPorcentaje_fa());
		attributes.put("porcentaje_el", getPorcentaje_el());
		attributes.put("porcentaje_te", getPorcentaje_te());
		attributes.put("porcentaje_br", getPorcentaje_br());
		attributes.put("porcentaje_ic", getPorcentaje_ic());
		attributes.put("porcentaje_ci", getPorcentaje_ci());
		attributes.put("retirado", getRetirado());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String numeroDocumento = (String)attributes.get("numeroDocumento");

		if (numeroDocumento != null) {
			setNumeroDocumento(numeroDocumento);
		}

		String tipoDocumento = (String)attributes.get("tipoDocumento");

		if (tipoDocumento != null) {
			setTipoDocumento(tipoDocumento);
		}

		String nombres = (String)attributes.get("nombres");

		if (nombres != null) {
			setNombres(nombres);
		}

		String apellidos = (String)attributes.get("apellidos");

		if (apellidos != null) {
			setApellidos(apellidos);
		}

		String cargo = (String)attributes.get("cargo");

		if (cargo != null) {
			setCargo(cargo);
		}

		Date fechaRegistro = (Date)attributes.get("fechaRegistro");

		if (fechaRegistro != null) {
			setFechaRegistro(fechaRegistro);
		}

		Date fechaModificacion = (Date)attributes.get("fechaModificacion");

		if (fechaModificacion != null) {
			setFechaModificacion(fechaModificacion);
		}

		String datos_personales = (String)attributes.get("datos_personales");

		if (datos_personales != null) {
			setDatos_personales(datos_personales);
		}

		String despacho = (String)attributes.get("despacho");

		if (despacho != null) {
			setDespacho(despacho);
		}

		String formacion_academica = (String)attributes.get(
				"formacion_academica");

		if (formacion_academica != null) {
			setFormacion_academica(formacion_academica);
		}

		String experiencia_laboral = (String)attributes.get(
				"experiencia_laboral");

		if (experiencia_laboral != null) {
			setExperiencia_laboral(experiencia_laboral);
		}

		String tiempo_experiencia = (String)attributes.get("tiempo_experiencia");

		if (tiempo_experiencia != null) {
			setTiempo_experiencia(tiempo_experiencia);
		}

		String bienes_y_rentas = (String)attributes.get("bienes_y_rentas");

		if (bienes_y_rentas != null) {
			setBienes_y_rentas(bienes_y_rentas);
		}

		String informacion_complementaria = (String)attributes.get(
				"informacion_complementaria");

		if (informacion_complementaria != null) {
			setInformacion_complementaria(informacion_complementaria);
		}

		String conflicto_intereses = (String)attributes.get(
				"conflicto_intereses");

		if (conflicto_intereses != null) {
			setConflicto_intereses(conflicto_intereses);
		}

		String archivo_declaracion_renta = (String)attributes.get(
				"archivo_declaracion_renta");

		if (archivo_declaracion_renta != null) {
			setArchivo_declaracion_renta(archivo_declaracion_renta);
		}

		String archivo_formulario_bienes = (String)attributes.get(
				"archivo_formulario_bienes");

		if (archivo_formulario_bienes != null) {
			setArchivo_formulario_bienes(archivo_formulario_bienes);
		}

		String archivo_hoja_vida = (String)attributes.get("archivo_hoja_vida");

		if (archivo_hoja_vida != null) {
			setArchivo_hoja_vida(archivo_hoja_vida);
		}

		Double porcentaje_dp = (Double)attributes.get("porcentaje_dp");

		if (porcentaje_dp != null) {
			setPorcentaje_dp(porcentaje_dp);
		}

		Double porcentaje_fa = (Double)attributes.get("porcentaje_fa");

		if (porcentaje_fa != null) {
			setPorcentaje_fa(porcentaje_fa);
		}

		Double porcentaje_el = (Double)attributes.get("porcentaje_el");

		if (porcentaje_el != null) {
			setPorcentaje_el(porcentaje_el);
		}

		Double porcentaje_te = (Double)attributes.get("porcentaje_te");

		if (porcentaje_te != null) {
			setPorcentaje_te(porcentaje_te);
		}

		Double porcentaje_br = (Double)attributes.get("porcentaje_br");

		if (porcentaje_br != null) {
			setPorcentaje_br(porcentaje_br);
		}

		Double porcentaje_ic = (Double)attributes.get("porcentaje_ic");

		if (porcentaje_ic != null) {
			setPorcentaje_ic(porcentaje_ic);
		}

		Double porcentaje_ci = (Double)attributes.get("porcentaje_ci");

		if (porcentaje_ci != null) {
			setPorcentaje_ci(porcentaje_ci);
		}

		String retirado = (String)attributes.get("retirado");

		if (retirado != null) {
			setRetirado(retirado);
		}
	}

	public String getNumeroDocumento() {
		if (_numeroDocumento == null) {
			return StringPool.BLANK;
		}
		else {
			return _numeroDocumento;
		}
	}

	public void setNumeroDocumento(String numeroDocumento) {
		_numeroDocumento = numeroDocumento;
	}

	public String getTipoDocumento() {
		if (_tipoDocumento == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipoDocumento;
		}
	}

	public void setTipoDocumento(String tipoDocumento) {
		_tipoDocumento = tipoDocumento;
	}

	public String getNombres() {
		if (_nombres == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombres;
		}
	}

	public void setNombres(String nombres) {
		_nombres = nombres;
	}

	public String getApellidos() {
		if (_apellidos == null) {
			return StringPool.BLANK;
		}
		else {
			return _apellidos;
		}
	}

	public void setApellidos(String apellidos) {
		_apellidos = apellidos;
	}

	public String getCargo() {
		if (_cargo == null) {
			return StringPool.BLANK;
		}
		else {
			return _cargo;
		}
	}

	public void setCargo(String cargo) {
		_cargo = cargo;
	}

	public Date getFechaRegistro() {
		return _fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		_fechaRegistro = fechaRegistro;
	}

	public Date getFechaModificacion() {
		return _fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		_fechaModificacion = fechaModificacion;
	}

	public String getDatos_personales() {
		if (_datos_personales == null) {
			return StringPool.BLANK;
		}
		else {
			return _datos_personales;
		}
	}

	public void setDatos_personales(String datos_personales) {
		_datos_personales = datos_personales;
	}

	public String getDespacho() {
		if (_despacho == null) {
			return StringPool.BLANK;
		}
		else {
			return _despacho;
		}
	}

	public void setDespacho(String despacho) {
		_despacho = despacho;
	}

	public String getFormacion_academica() {
		if (_formacion_academica == null) {
			return StringPool.BLANK;
		}
		else {
			return _formacion_academica;
		}
	}

	public void setFormacion_academica(String formacion_academica) {
		_formacion_academica = formacion_academica;
	}

	public String getExperiencia_laboral() {
		if (_experiencia_laboral == null) {
			return StringPool.BLANK;
		}
		else {
			return _experiencia_laboral;
		}
	}

	public void setExperiencia_laboral(String experiencia_laboral) {
		_experiencia_laboral = experiencia_laboral;
	}

	public String getTiempo_experiencia() {
		if (_tiempo_experiencia == null) {
			return StringPool.BLANK;
		}
		else {
			return _tiempo_experiencia;
		}
	}

	public void setTiempo_experiencia(String tiempo_experiencia) {
		_tiempo_experiencia = tiempo_experiencia;
	}

	public String getBienes_y_rentas() {
		if (_bienes_y_rentas == null) {
			return StringPool.BLANK;
		}
		else {
			return _bienes_y_rentas;
		}
	}

	public void setBienes_y_rentas(String bienes_y_rentas) {
		_bienes_y_rentas = bienes_y_rentas;
	}

	public String getInformacion_complementaria() {
		if (_informacion_complementaria == null) {
			return StringPool.BLANK;
		}
		else {
			return _informacion_complementaria;
		}
	}

	public void setInformacion_complementaria(String informacion_complementaria) {
		_informacion_complementaria = informacion_complementaria;
	}

	public String getConflicto_intereses() {
		if (_conflicto_intereses == null) {
			return StringPool.BLANK;
		}
		else {
			return _conflicto_intereses;
		}
	}

	public void setConflicto_intereses(String conflicto_intereses) {
		_conflicto_intereses = conflicto_intereses;
	}

	public String getArchivo_declaracion_renta() {
		if (_archivo_declaracion_renta == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_declaracion_renta;
		}
	}

	public void setArchivo_declaracion_renta(String archivo_declaracion_renta) {
		_archivo_declaracion_renta = archivo_declaracion_renta;
	}

	public String getArchivo_formulario_bienes() {
		if (_archivo_formulario_bienes == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_formulario_bienes;
		}
	}

	public void setArchivo_formulario_bienes(String archivo_formulario_bienes) {
		_archivo_formulario_bienes = archivo_formulario_bienes;
	}

	public String getArchivo_hoja_vida() {
		if (_archivo_hoja_vida == null) {
			return StringPool.BLANK;
		}
		else {
			return _archivo_hoja_vida;
		}
	}

	public void setArchivo_hoja_vida(String archivo_hoja_vida) {
		_archivo_hoja_vida = archivo_hoja_vida;
	}

	public double getPorcentaje_dp() {
		return _porcentaje_dp;
	}

	public void setPorcentaje_dp(double porcentaje_dp) {
		_porcentaje_dp = porcentaje_dp;
	}

	public double getPorcentaje_fa() {
		return _porcentaje_fa;
	}

	public void setPorcentaje_fa(double porcentaje_fa) {
		_porcentaje_fa = porcentaje_fa;
	}

	public double getPorcentaje_el() {
		return _porcentaje_el;
	}

	public void setPorcentaje_el(double porcentaje_el) {
		_porcentaje_el = porcentaje_el;
	}

	public double getPorcentaje_te() {
		return _porcentaje_te;
	}

	public void setPorcentaje_te(double porcentaje_te) {
		_porcentaje_te = porcentaje_te;
	}

	public double getPorcentaje_br() {
		return _porcentaje_br;
	}

	public void setPorcentaje_br(double porcentaje_br) {
		_porcentaje_br = porcentaje_br;
	}

	public double getPorcentaje_ic() {
		return _porcentaje_ic;
	}

	public void setPorcentaje_ic(double porcentaje_ic) {
		_porcentaje_ic = porcentaje_ic;
	}

	public double getPorcentaje_ci() {
		return _porcentaje_ci;
	}

	public void setPorcentaje_ci(double porcentaje_ci) {
		_porcentaje_ci = porcentaje_ci;
	}

	public String getRetirado() {
		if (_retirado == null) {
			return StringPool.BLANK;
		}
		else {
			return _retirado;
		}
	}

	public void setRetirado(String retirado) {
		_retirado = retirado;
	}

	@Override
	public usuario_data toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (usuario_data)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		usuario_dataImpl usuario_dataImpl = new usuario_dataImpl();

		usuario_dataImpl.setNumeroDocumento(getNumeroDocumento());
		usuario_dataImpl.setTipoDocumento(getTipoDocumento());
		usuario_dataImpl.setNombres(getNombres());
		usuario_dataImpl.setApellidos(getApellidos());
		usuario_dataImpl.setCargo(getCargo());
		usuario_dataImpl.setFechaRegistro(getFechaRegistro());
		usuario_dataImpl.setFechaModificacion(getFechaModificacion());
		usuario_dataImpl.setDatos_personales(getDatos_personales());
		usuario_dataImpl.setDespacho(getDespacho());
		usuario_dataImpl.setFormacion_academica(getFormacion_academica());
		usuario_dataImpl.setExperiencia_laboral(getExperiencia_laboral());
		usuario_dataImpl.setTiempo_experiencia(getTiempo_experiencia());
		usuario_dataImpl.setBienes_y_rentas(getBienes_y_rentas());
		usuario_dataImpl.setInformacion_complementaria(getInformacion_complementaria());
		usuario_dataImpl.setConflicto_intereses(getConflicto_intereses());
		usuario_dataImpl.setArchivo_declaracion_renta(getArchivo_declaracion_renta());
		usuario_dataImpl.setArchivo_formulario_bienes(getArchivo_formulario_bienes());
		usuario_dataImpl.setArchivo_hoja_vida(getArchivo_hoja_vida());
		usuario_dataImpl.setPorcentaje_dp(getPorcentaje_dp());
		usuario_dataImpl.setPorcentaje_fa(getPorcentaje_fa());
		usuario_dataImpl.setPorcentaje_el(getPorcentaje_el());
		usuario_dataImpl.setPorcentaje_te(getPorcentaje_te());
		usuario_dataImpl.setPorcentaje_br(getPorcentaje_br());
		usuario_dataImpl.setPorcentaje_ic(getPorcentaje_ic());
		usuario_dataImpl.setPorcentaje_ci(getPorcentaje_ci());
		usuario_dataImpl.setRetirado(getRetirado());

		usuario_dataImpl.resetOriginalValues();

		return usuario_dataImpl;
	}

	public int compareTo(usuario_data usuario_data) {
		String primaryKey = usuario_data.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		usuario_data usuario_data = null;

		try {
			usuario_data = (usuario_data)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = usuario_data.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<usuario_data> toCacheModel() {
		usuario_dataCacheModel usuario_dataCacheModel = new usuario_dataCacheModel();

		usuario_dataCacheModel.numeroDocumento = getNumeroDocumento();

		String numeroDocumento = usuario_dataCacheModel.numeroDocumento;

		if ((numeroDocumento != null) && (numeroDocumento.length() == 0)) {
			usuario_dataCacheModel.numeroDocumento = null;
		}

		usuario_dataCacheModel.tipoDocumento = getTipoDocumento();

		String tipoDocumento = usuario_dataCacheModel.tipoDocumento;

		if ((tipoDocumento != null) && (tipoDocumento.length() == 0)) {
			usuario_dataCacheModel.tipoDocumento = null;
		}

		usuario_dataCacheModel.nombres = getNombres();

		String nombres = usuario_dataCacheModel.nombres;

		if ((nombres != null) && (nombres.length() == 0)) {
			usuario_dataCacheModel.nombres = null;
		}

		usuario_dataCacheModel.apellidos = getApellidos();

		String apellidos = usuario_dataCacheModel.apellidos;

		if ((apellidos != null) && (apellidos.length() == 0)) {
			usuario_dataCacheModel.apellidos = null;
		}

		usuario_dataCacheModel.cargo = getCargo();

		String cargo = usuario_dataCacheModel.cargo;

		if ((cargo != null) && (cargo.length() == 0)) {
			usuario_dataCacheModel.cargo = null;
		}

		Date fechaRegistro = getFechaRegistro();

		if (fechaRegistro != null) {
			usuario_dataCacheModel.fechaRegistro = fechaRegistro.getTime();
		}
		else {
			usuario_dataCacheModel.fechaRegistro = Long.MIN_VALUE;
		}

		Date fechaModificacion = getFechaModificacion();

		if (fechaModificacion != null) {
			usuario_dataCacheModel.fechaModificacion = fechaModificacion.getTime();
		}
		else {
			usuario_dataCacheModel.fechaModificacion = Long.MIN_VALUE;
		}

		usuario_dataCacheModel.datos_personales = getDatos_personales();

		String datos_personales = usuario_dataCacheModel.datos_personales;

		if ((datos_personales != null) && (datos_personales.length() == 0)) {
			usuario_dataCacheModel.datos_personales = null;
		}

		usuario_dataCacheModel.despacho = getDespacho();

		String despacho = usuario_dataCacheModel.despacho;

		if ((despacho != null) && (despacho.length() == 0)) {
			usuario_dataCacheModel.despacho = null;
		}

		usuario_dataCacheModel.formacion_academica = getFormacion_academica();

		String formacion_academica = usuario_dataCacheModel.formacion_academica;

		if ((formacion_academica != null) &&
				(formacion_academica.length() == 0)) {
			usuario_dataCacheModel.formacion_academica = null;
		}

		usuario_dataCacheModel.experiencia_laboral = getExperiencia_laboral();

		String experiencia_laboral = usuario_dataCacheModel.experiencia_laboral;

		if ((experiencia_laboral != null) &&
				(experiencia_laboral.length() == 0)) {
			usuario_dataCacheModel.experiencia_laboral = null;
		}

		usuario_dataCacheModel.tiempo_experiencia = getTiempo_experiencia();

		String tiempo_experiencia = usuario_dataCacheModel.tiempo_experiencia;

		if ((tiempo_experiencia != null) && (tiempo_experiencia.length() == 0)) {
			usuario_dataCacheModel.tiempo_experiencia = null;
		}

		usuario_dataCacheModel.bienes_y_rentas = getBienes_y_rentas();

		String bienes_y_rentas = usuario_dataCacheModel.bienes_y_rentas;

		if ((bienes_y_rentas != null) && (bienes_y_rentas.length() == 0)) {
			usuario_dataCacheModel.bienes_y_rentas = null;
		}

		usuario_dataCacheModel.informacion_complementaria = getInformacion_complementaria();

		String informacion_complementaria = usuario_dataCacheModel.informacion_complementaria;

		if ((informacion_complementaria != null) &&
				(informacion_complementaria.length() == 0)) {
			usuario_dataCacheModel.informacion_complementaria = null;
		}

		usuario_dataCacheModel.conflicto_intereses = getConflicto_intereses();

		String conflicto_intereses = usuario_dataCacheModel.conflicto_intereses;

		if ((conflicto_intereses != null) &&
				(conflicto_intereses.length() == 0)) {
			usuario_dataCacheModel.conflicto_intereses = null;
		}

		usuario_dataCacheModel.archivo_declaracion_renta = getArchivo_declaracion_renta();

		String archivo_declaracion_renta = usuario_dataCacheModel.archivo_declaracion_renta;

		if ((archivo_declaracion_renta != null) &&
				(archivo_declaracion_renta.length() == 0)) {
			usuario_dataCacheModel.archivo_declaracion_renta = null;
		}

		usuario_dataCacheModel.archivo_formulario_bienes = getArchivo_formulario_bienes();

		String archivo_formulario_bienes = usuario_dataCacheModel.archivo_formulario_bienes;

		if ((archivo_formulario_bienes != null) &&
				(archivo_formulario_bienes.length() == 0)) {
			usuario_dataCacheModel.archivo_formulario_bienes = null;
		}

		usuario_dataCacheModel.archivo_hoja_vida = getArchivo_hoja_vida();

		String archivo_hoja_vida = usuario_dataCacheModel.archivo_hoja_vida;

		if ((archivo_hoja_vida != null) && (archivo_hoja_vida.length() == 0)) {
			usuario_dataCacheModel.archivo_hoja_vida = null;
		}

		usuario_dataCacheModel.porcentaje_dp = getPorcentaje_dp();

		usuario_dataCacheModel.porcentaje_fa = getPorcentaje_fa();

		usuario_dataCacheModel.porcentaje_el = getPorcentaje_el();

		usuario_dataCacheModel.porcentaje_te = getPorcentaje_te();

		usuario_dataCacheModel.porcentaje_br = getPorcentaje_br();

		usuario_dataCacheModel.porcentaje_ic = getPorcentaje_ic();

		usuario_dataCacheModel.porcentaje_ci = getPorcentaje_ci();

		usuario_dataCacheModel.retirado = getRetirado();

		String retirado = usuario_dataCacheModel.retirado;

		if ((retirado != null) && (retirado.length() == 0)) {
			usuario_dataCacheModel.retirado = null;
		}

		return usuario_dataCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(53);

		sb.append("{numeroDocumento=");
		sb.append(getNumeroDocumento());
		sb.append(", tipoDocumento=");
		sb.append(getTipoDocumento());
		sb.append(", nombres=");
		sb.append(getNombres());
		sb.append(", apellidos=");
		sb.append(getApellidos());
		sb.append(", cargo=");
		sb.append(getCargo());
		sb.append(", fechaRegistro=");
		sb.append(getFechaRegistro());
		sb.append(", fechaModificacion=");
		sb.append(getFechaModificacion());
		sb.append(", datos_personales=");
		sb.append(getDatos_personales());
		sb.append(", despacho=");
		sb.append(getDespacho());
		sb.append(", formacion_academica=");
		sb.append(getFormacion_academica());
		sb.append(", experiencia_laboral=");
		sb.append(getExperiencia_laboral());
		sb.append(", tiempo_experiencia=");
		sb.append(getTiempo_experiencia());
		sb.append(", bienes_y_rentas=");
		sb.append(getBienes_y_rentas());
		sb.append(", informacion_complementaria=");
		sb.append(getInformacion_complementaria());
		sb.append(", conflicto_intereses=");
		sb.append(getConflicto_intereses());
		sb.append(", archivo_declaracion_renta=");
		sb.append(getArchivo_declaracion_renta());
		sb.append(", archivo_formulario_bienes=");
		sb.append(getArchivo_formulario_bienes());
		sb.append(", archivo_hoja_vida=");
		sb.append(getArchivo_hoja_vida());
		sb.append(", porcentaje_dp=");
		sb.append(getPorcentaje_dp());
		sb.append(", porcentaje_fa=");
		sb.append(getPorcentaje_fa());
		sb.append(", porcentaje_el=");
		sb.append(getPorcentaje_el());
		sb.append(", porcentaje_te=");
		sb.append(getPorcentaje_te());
		sb.append(", porcentaje_br=");
		sb.append(getPorcentaje_br());
		sb.append(", porcentaje_ic=");
		sb.append(getPorcentaje_ic());
		sb.append(", porcentaje_ci=");
		sb.append(getPorcentaje_ci());
		sb.append(", retirado=");
		sb.append(getRetirado());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(82);

		sb.append("<model><model-name>");
		sb.append("com.co.csj.service.model.usuario_data");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>numeroDocumento</column-name><column-value><![CDATA[");
		sb.append(getNumeroDocumento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipoDocumento</column-name><column-value><![CDATA[");
		sb.append(getTipoDocumento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombres</column-name><column-value><![CDATA[");
		sb.append(getNombres());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>apellidos</column-name><column-value><![CDATA[");
		sb.append(getApellidos());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cargo</column-name><column-value><![CDATA[");
		sb.append(getCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaRegistro</column-name><column-value><![CDATA[");
		sb.append(getFechaRegistro());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fechaModificacion</column-name><column-value><![CDATA[");
		sb.append(getFechaModificacion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>datos_personales</column-name><column-value><![CDATA[");
		sb.append(getDatos_personales());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>despacho</column-name><column-value><![CDATA[");
		sb.append(getDespacho());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>formacion_academica</column-name><column-value><![CDATA[");
		sb.append(getFormacion_academica());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>experiencia_laboral</column-name><column-value><![CDATA[");
		sb.append(getExperiencia_laboral());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiempo_experiencia</column-name><column-value><![CDATA[");
		sb.append(getTiempo_experiencia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bienes_y_rentas</column-name><column-value><![CDATA[");
		sb.append(getBienes_y_rentas());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>informacion_complementaria</column-name><column-value><![CDATA[");
		sb.append(getInformacion_complementaria());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>conflicto_intereses</column-name><column-value><![CDATA[");
		sb.append(getConflicto_intereses());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_declaracion_renta</column-name><column-value><![CDATA[");
		sb.append(getArchivo_declaracion_renta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_formulario_bienes</column-name><column-value><![CDATA[");
		sb.append(getArchivo_formulario_bienes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>archivo_hoja_vida</column-name><column-value><![CDATA[");
		sb.append(getArchivo_hoja_vida());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_dp</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_dp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_fa</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_fa());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_el</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_el());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_te</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_te());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_br</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_br());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_ic</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_ic());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>porcentaje_ci</column-name><column-value><![CDATA[");
		sb.append(getPorcentaje_ci());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>retirado</column-name><column-value><![CDATA[");
		sb.append(getRetirado());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = usuario_data.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			usuario_data.class
		};
	private String _numeroDocumento;
	private String _tipoDocumento;
	private String _nombres;
	private String _apellidos;
	private String _cargo;
	private Date _fechaRegistro;
	private Date _fechaModificacion;
	private String _datos_personales;
	private String _despacho;
	private String _formacion_academica;
	private String _experiencia_laboral;
	private String _tiempo_experiencia;
	private String _bienes_y_rentas;
	private String _informacion_complementaria;
	private String _conflicto_intereses;
	private String _archivo_declaracion_renta;
	private String _archivo_formulario_bienes;
	private String _archivo_hoja_vida;
	private double _porcentaje_dp;
	private double _porcentaje_fa;
	private double _porcentaje_el;
	private double _porcentaje_te;
	private double _porcentaje_br;
	private double _porcentaje_ic;
	private double _porcentaje_ci;
	private String _retirado;
	private usuario_data _escapedModelProxy;
}